### ISSUE TITLE
[BUG] Package failure

### ISSUE THREAD

**Issue by Getn67** [Renaud11232/OctoPrint-Marlin-Flasher#88] opened 2022-09-12 00:36 UTC
**Describe the bug**

Could not locate the correct package for plugin to function properly.

Rpi 3+ B
Octopi

**To Reproduce**

**Expected behavior**

necessary package installed to successfully flash printer

**Screenshots**

**Version of OctoPrint-Marlin-Flasher**

1.0.3 installed via plugin manager

**Server configuration**
 - OS: https://github.com/guysoft/OctoPi (raspbian)
 - Browser Microsoft Edge
Version 105.0.1343.27 (Official build) (64-bit)
 - Python version Python 3.7.3

Tool Manager: Installing platformio/tool-dfuutil @ ^1.11.0
Error: Could not find the package with 'platformio/tool-dfuutil @ ^1.11.0' requirements for your system 'linux_armv7l'

Upload your logs here

**Browser console logs**

Upload the logs of your browser here, on Chrome press F12

**Comment by Renaud11232** [comment] 2022-09-13 15:07
Hello,

This looks like an issue with a package not being available for your CPU achitecture. If that's the case, I can't do much about it.
Just to make sure, can you provide the following info : 
* When does this issue appear ? (When installing Platformio/attempting to flash the firmware/other)
* Can you provide the full OctoPrint logs ?
* What version of OctoPi are you using ?

Thanks

**Comment by Getn67** [comment] 2022-09-17 18:29
1. when attempting to flash firmware
2. 
![image](https://user-images.githubusercontent.com/51862012/190871442-e558bdc9-65a4-433b-a845-f05350aa8174.png)
Which log would you like?
3. .18 the latest release.

**Comment by Renaud11232** [comment] 2022-09-17 21:02
You need to set `octoprint.plugins.marlin_flasher` to `DEBUG`. Once that is done, reproduce the error and download the `octiprint.log` file in `Settings > Logging` and upload it link it to this issue.
You can then unset the log level of `octoprint.plugins.marlin_flasher`

**Comment by Getn67** [comment] 2022-09-18 03:36
[octoprint (1).log](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/files/9593004/octoprint.1.log)

Hopefully this has everything you need.

**Comment by Renaud11232** [comment] 2022-09-18 07:16
Hello,

As I suspected, this is an issue with PlatformIO tools not being available for armv7l at a specific version, sadly, there's nothing I can do to fix that. It can however get fixed in the future, but I have no control over that.

Since this is not an issue with the plugin itself, I'll be closing this issue.

Sorry for the inconvenience

**Closed as completed by Renaud11232** 2022-09-18 07:16 UTC
Labels: bug

**Comment by d4icon** [comment] 2023-01-31 08:43
same problem here.
Raspberry pi 3, last version octoprint.


Any solution?
