### ISSUE TITLE
web ui stuck on wizard

### ISSUE THREAD

**Issue by felixmxr** [Renaud11232/OctoPrint-Marlin-Flasher#63] opened 2020-12-25 21:56 UTC
similar to https://github.com/Renaud11232/OctoPrint-Marlin-Flasher/issues/32
clicking finish doesnt remove the wizard

**screenshot**
![image](https://user-images.githubusercontent.com/5577153/103142499-549dc880-4704-11eb-8bbe-d11ede7ff651.png)

**octoprint log**
` octoprint.util.comm - INFO - Connecting to port /dev/ttyAMA0, baudrate 250000
2020-12-25 21:41:34,767 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial connection" to "Connecting"
2020-12-25 21:41:34,790 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2020-12-25 21:41:34,794 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-12-25 21:41:34,803 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2020-12-25 21:41:35,030 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-12-25 21:41:35,058 - octoprint.util.comm - INFO - Changing monitoring state from "Connecting" to "Operational"
2020-12-25 21:41:35,141 - octoprint.plugin - ERROR - Error while calling plugin marlin_flasher
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_marlin_flasher/__init__.py", line 100, in on_event
    self.__flasher.handle_connected_event()
AttributeError: 'MarlinFlasherPlugin' object has no attribute '_MarlinFlasherPlugin__flasher'
2020-12-25 21:41:35,248 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2020-12-25 21:41:35,309 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin 2.0.5.3 (GitHub)"
2020-12-25 21:41:35,371 - octoprint.plugins.ABL_Expert - INFO - self.printer_cap[eeprom] is now 1
`

**web console**
![image](https://user-images.githubusercontent.com/5577153/103142543-13f27f00-4705-11eb-8316-34f9ebfda7c1.png)

**web console error detail**
![image](https://user-images.githubusercontent.com/5577153/103142557-456b4a80-4705-11eb-8ec9-61655393f84d.png)

any suggestions i could try out?

**Comment by Renaud11232** [comment] 2020-12-26 11:21
Hello, I have a few questions

In the web console, are there any errors before the ones you showed ?

Is there any error in the console that appears when you click "Finish" ?

Did you set the path to your arduinocli executable ?

Is there any error shown on the web page itself. Like a little red notification. And what does it say ?

Thanks

**Comment by andymk3** [comment] 2020-12-29 13:44
Same issue here. I had to remove the plugin via SSH to use my printer again with this:

`~/oprint/bin/pip uninstall OctoPrint-Marlin-Flasher`

**Comment by Renaud11232** [comment] 2021-01-20 16:14
I managed to reproduce the problem.

It looks like the issue comes from another plugin that prevents the Setup Wizard from saving settings.
@andymk3 Can you confirm you had the plugin `PSU Control` installed when you tried to install my plugin ?

I can see from the screenshot that @felixmxr had it installed.

**Comment by felixmxr** [comment] 2021-01-20 16:59
i have removed psu control and now your plugin works
thanks for helping.
sorry for not responding previously. i couldnt find any helpful info earlier

**Comment by Renaud11232** [comment] 2021-02-01 19:25
This issue has been fixed in `PSU Control 0.1.11`
[OctoPrint-SmartPreheat](https://github.com/kantlivelong/OctoPrint-SmartPreheat) is also affected and a fix will be released shortly.

I'm closing this since the cause issue is now fixed

**Closed as completed by Renaud11232** 2021-02-01 19:25 UTC
Labels: bug
