### ISSUE TITLE
[BUG] Error: Could not find the package [...] for your system 'linux_armv7l'

### ISSUE THREAD

**Issue by dumbnerd08** [Renaud11232/OctoPrint-Marlin-Flasher#93] opened 2023-04-16 01:27 UTC
**Describe the bug**

When I attempt to compile my firmware, I get the following issue:

```
Tool Manager: Installing platformio/toolchain-gccarmnoneeabi @ ~1.90201.0
Error: Could not find the package with 'platformio/toolchain-gccarmnoneeabi @ ~1.90201.0' requirements for your system 'linux_armv7l'
```

**To Reproduce**

1. Go to 'Marlin Flasher'
2. Upload .ZIP file with the STM32F103RE_creality environment
3. Click 'Flash'
4. Select the same environment as in the PlatformIO.INI file
5. 'Compile;'
6. See error

**Expected behavior**

I have not yet had a successful compile, but likely what I'd expect is for it to compile and flash the firmware

**Screenshots**

**Version of OctoPrint-Marlin-Flasher**

What version are you using, how was it installed ?

Latest version

Installed via octoprint plugin manager

**Server configuration**
 - OS: Octopi (Raspbian)
 - Browser: Edge on Fedora Linux (im a linux user btw) (did u hear me im a linux user)
 - Python version: 3.9.2
**OctoPrint logs with `octoprint.plugins.marlin_flasher` set to DEBUG**

**Browser console logs**

**Comment by Renaud11232** [comment] 2023-04-17 15:45
Hello,

This issue is a duplicate of #88.

Sadly this is a problem with PlatformIO dependencies not being available for `armv7`. I don't have any control over that.

Since this is not an issue with the plugin itself, I will close this issue.

This means there is currently no way to directly compile the firmware on the Raspberry Pi for some boards/configurations using this plugin.

The PlatformIO remote upload feature could work arround this (#71). But there are some problems preventing me from integrating this into the plugin.

Sorry for the inconvinience.

**Closed as not planned by Renaud11232** 2023-04-17 15:45 UTC
Labels: duplicate
