### ISSUE TITLE
the configured path does not point to an arduino.cli executable

### ISSUE THREAD

**Issue by CrystalJP** [Renaud11232/OctoPrint-Marlin-Flasher#70] opened 2021-02-24 00:39 UTC
My file pathing seems fine, but I keep getting this error. I'm trying to install a hex file but I can't even get to the main screen.

I can run it from cmd with no problems.

**Comment by Renaud11232** [comment] 2021-02-24 15:41
Hello,

I'm closing this issue since it's a duplicate of #62.
I've answered on that issue.

Thanks

**Closed as completed by Renaud11232** 2021-02-24 15:41 UTC
Labels: duplicate
