### ISSUE TITLE
[BUG] Could not find package toolchain-gccarmnoneeabi

### ISSUE THREAD

**Issue by leamikmik** [Renaud11232/OctoPrint-Marlin-Flasher#95] opened 2024-01-25 17:57 UTC
**Describe the bug**

When trying to flash Marlin using PlatformIO it crashes because of a missing dependency.

**To Reproduce**

**Error output**
```
Processing STM32F103RE_creality (board: genericSTM32F103RE; platform: ststm32@~12.1; framework: arduino)
--------------------------------------------------------------------------------
Tool Manager: Installing platformio/toolchain-gccarmnoneeabi @ ~1.90201.0
UnknownPackageError: Could not find the package with 'platformio/toolchain-gccarmnoneeabi @ ~1.90201.0' requirements for your system 'linux_aarch64'
```
**Expected behavior**

Successful flash.

**Version of OctoPrint-Marlin-Flasher**

1.0.7, installed using plugin manager

**Server configuration**
 - OS: RPI 4 Model B

**Comment by Renaud11232** [comment] 2024-01-25 20:06
Hello,

This is a duplicate of #93 and #88.
This is an issue with PlatformIO packages not being available for a given architecture.
I'm aware this seems to affect an increasing number of users, sadly there's nothing I can do about it.

**Closed as not planned by Renaud11232** 2024-01-25 20:06 UTC
Labels: duplicate
